plugins {
    id "com.android.application"
}

android {
    namespace "com.gytxtx.openjbd"
    compileSdk 34

    defaultConfig {
        applicationId "com.gytxtx.openjbd"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "0.1.0"
    }
}

dependencies {
    implementation "androidx.fragment:fragment:1.6.2"
    implementation "com.google.android.material:material:1.10.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
}
